version: "3.8"
services:
  db:
    image: postgis/postgis:16-3.5
    container_name: postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: osmdata
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

volumes:
  postgis_data:
  grafana_data:
